### PR TITLE
Port Minitest integration from Mutant

### LINKED ISSUE #93: Port minitest integration from mutant
Mutant recently gained minitest integration. It would be nice to have that ported to mutest.

### PR DESCRIPTION
**Pull request by mvz**
Fixes #93.

### CODE REVIEW

**Comment by mbj** [comment]
@mvz If you take commits from me verbatim 1:1 I think you should include attribution in the respective source file.

**Comment by mvz** [comment]
@mbj I empathize with your position but I did not take commits verbatim otherwise I would have left the commit message and authorship intact as I did in #94. I can try to redo the port by actually cherry-picking the commits if you would prefer?

**Comment by mvz** [comment]
@mbj I cherry-picked the mutant-minitest commit to ensure proper attribution.

**Comment by mbj** [comment]
> @mbj I empathize with your position but I did not take commits verbatim otherwise I would have left the commit message and authorship intact as I did in #94. I can try to redo the port by actually cherry-picking the commits if you would prefer?

Well, just renaming the namespace does not really make it "your" work. The minitest integration minus renames is 99% my code. (Just as the rest of mutest but the exclusion feature and the renames + some whitespace fixes).

**Comment by mbj** [comment]
> @mbj I cherry-picked the mutant-minitest commit to ensure proper attribution.

fair.

**Comment by mbj** [comment]
@mvz, @dgollahon Please note the effect of: https://github.com/mbj/mutant/pull/836

Any code I add after this point is not MIT licenced. So you cannot take it, and I (currently until I finish the license transition) do not offer an OSS licence for my future work on the project.

This obviously does not affect past releases and past repo state. New code / new releases: new rules.

**Comment by mbj** [comment]
@mvz Also it just came to my notice that Arkency sponsored this work (and all the testing around it). I recommend to at mimium replicate the sponsoring notice I've got in the mutant Readme.

**Comment by mvz** [comment]
> I recommend to at mimium replicate the sponsoring notice I've got in the mutant Readme.

I'll update the Readme with such a notice.

**Comment by mvz** [comment]
@mbj:
> Well, just renaming the namespace does not really make it "your" work.

Indeed, nor did I attempt to pass it off as such (as per the original commit message), and I have to strongly reject any suggestion that I did so.

Again, I did not at first use any commits from mutant, but simply copied the code.

@mbj:
> And just to clarify this PR (even without attribution) is totally fine from a licensing point of view.

Yet it seems you take issue with this fork of mutant. It would be helpful if these problems were clarified to prevent discussions like the present one.

**Comment by mbj** [comment]
> Yet it seems you take issue with this fork of mutant. It would be helpful if these problems were clarified to prevent discussions like the present one.

I take issue that I constantly have to fight for attribution of my work and the trust placed in me by sponsors. Hence I'm targeting to change mutants license to one that ensures proper attribution is done.

**Comment by mvz** [comment]
> I constantly have to fight for attribution of my work

I'm sorry you feel that way. It seems to me mutant was named consistently in this fork and in the present pull request.

**Comment by mbj** [comment]
> > 
> 
> You really need to stop making these veiled accusations.

Mhh the sponsoring notice inside the mutant code base, sais "this integration was sponsored" and as its inside the mutant code base its clear mutant was sponsored.

But if you take it 1:1 to mutest, without specifying the sponsoring was for mutant, naturally a first time reader would assume it was mutest who sponsored.

That is an easy to understand fact. 

And I'm not here to explain you on how to correctly attribute work and or avoid these problems. Its your responsibility not mine.

**Comment by mbj** [comment]
I'm only here to guard my interest, and the interest of my sponsors. And I hate having to do this.

**Comment by mvz** [comment]
> And I'm not here to explain you on how to correctly attribute work and or avoid these problems. Its your responsibility not mine.

It is your responsibility to state requirements upfront through licensing. Because of this, I'm glad to see you change the license of mutant.

> I'm only here to guard my interest, and the interest of my sponsors. And I hate having to do this.

If you would go about it in a way that expresses assumption of good faith on the part of the other people involved, we would all have an easier time.

As things stand, I don't have time or energy to deal with these discussions in the future, and have therefore withdrawn this pull request.

**Comment by mbj** [comment]
your call. So far the last issue I had was that the sponsoring notice had "project targeting" issues as its formulated in a way its targeting "the project you read it on". As mutest re-used the sponsored code, you should just have added "sponsoring was done for the mutant" project and you where done.

Note that the license at the time you took the code does not demand any of this, feel free to not attribute at all. It would be ethically wrong from my point of view. But again the license would permit no attribution.

**Pull request closed without merging**
